language: bash
sudo: required
dist: trusty
cache:
  directories:
    - ~/pbuilder
before_install:
  - sudo apt-get -q update
install:
before_script:
script:
  - ./package.sh ${DISTRIBUTION} ${ARCHITECTURE}
after_failure:
after_success:
env:
  matrix:
    - DISTRIBUTION=xenial ARCHITECTURE=i386
    - DISTRIBUTION=xenial ARCHITECTURE=amd64
